version: "3"
services:
  database:
    image: postgres
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - "5432:5432"
    expose:
      - 5432
  backend:
    build:
      context: ./backend
      dockerfile: backend.Dockerfile
    ports:
      - "3000:3000"

    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_DATABASE=${DB_DATABASE}
      - DB_PASSWORD=${DB_PASSWORD}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - "./backend:/app"
    depends_on:
      - database
  frontend:
    build:
      context: ./frontend
      dockerfile: frontend.Dockerfile
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    environment:
      - VITE_BACKEND_URL=http://localhost:3000
networks:
  default:
    external: true
    name: web
