version: "3"
services:
  database:
    image: postgres
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    #    ports:
    #      - "5432:5432"
    volumes:
      - ./volumes/db:/var/lib/postgresql/data
    expose:
      - 5432
  backend:
    build:
      context: ./backend
      dockerfile: backend.Dockerfile
      target: dev_img
    ports:
      - "3000:3000"

    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_DATABASE=${DB_DATABASE}
      - DB_PASSWORD=${DB_PASSWORD}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - "./backend:/app"
    depends_on:
      - database
    profiles:
      - ""
      - "dev"
  frontend:
    build:
      context: ./frontend
      dockerfile: frontend.Dockerfile
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    environment:
      - VITE_BACKEND_URL=http://localhost:3000
    profiles:
      - ""
      - "dev"
    backend-p:
      build:
        context: ./backend
        dockerfile: backend.Dockerfile
        target: prod_img
      ports:
        - "127.0.0.1:3000:3000"
      environment:
        - DB_HOST=${DB_HOST}
        - DB_PORT=${DB_PORT}
        - DB_USERNAME=${DB_USERNAME}
        - DB_DATABASE=${DB_DATABASE}
        - DB_PASSWORD=${DB_PASSWORD}
        - DATABASE_URL=${DATABASE_URL}
      depends_on:
        - database
      profiles:
        - "prod"
    frontend-p:
      build:
        context: ./frontend
        dockerfile: frontend.Dockerfile
      working_dir: /app
      ports:
        - "127.0.0.1:5173:5173"
      environment:
        - VITE_BACKEND_URL=http://localhost:3000
      profiles:
        - "prod"
